services:
  mc-server:
    image: itzg/minecraft-server:latest
    container_name: mc-server
    ports:
      - "60068:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.1"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "potato"
    volumes:
      - "./server 2025:/data"
